### ISSUE TITLE
buildymcbuild Qs

### ISSUE THREAD

**Issue by trentm** [joyent/buildymcbuildface#2]
1. does "pkg_add" handle package deps?
2. do we still want the upload to /Joyent_Dev/public/builds/... area?
3. "MG is no longer needed so the total amount of code involved is reduced."
   Well, similar code moved from MG to buildymcbuildface.
4. Another benefit: All build logic in the individual repos makes associating
   changes with a commit much cleaner.
5. why is build.json not called "Buildymcbuildfile"?
6. https://github.com/joyent/sdc-papi/compare/buildymcbuildface?expand=1#diff-b67911656ef5d18c4ae36cb6741b7965R47
   Would be nice to avoid external dep on `json` install. For a build on
   SmartOS, that is fine. ... but this'd break for `make check` or other
   local dev tasks on Mac if the user hadn't `npm install -g json`d.
7. TRY_BRANCH support? Not yet. How should we do that?
   Happy to discuss that and handling for "bloat" deps (also supporting
   TRY_BRANCH for them).

**Comment by joshwilsdon** [comment]
1. pkg_add does appear to handle deps.
2. good question. Probably?
3. yep.
4. yep.
5. 🤔
6. should we bundle it like MG does?
7. Since the deps are handled explicitly by the repo, it's only the bloat deps that would make sense to have TRY_BRANCH work for. So when we write the tool that downloads that stuff, we could handle this there. If those deps are moved into being modules though it'll be up to the branch to point to correct versions.

**Comment by trentm** [comment]
- Q2. Probably keep it for starters. Can come back to seeing about ditching that.
- Q6. I think so, yes. The `json` dep is small.
- Q7. Actually, yah... getting the selected bloat dep to depend on an explicit committed config value in the repo sounds better. I.e. the concept of TRY_BRANCH goes away I think. Not sure about platform  and headnode builds, but that's a separate story.
